version: '3'
services:
  omada:
    build: .
    environment:
      - OMADA_HTTP_PORT=8080
      - OMADA_HTTPS_PORT=8443
      - OMADA_MONGO_HOST=mongo
      - OMADA_MONGO_PORT=27017
      - OMADA_MONGO_DATABASE=omada
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - omada

  mongo:
    image: mongo:3.2
    networks:
      - omada
    # Port forwarding just for debugging
    ports:
      - 27017:27017

networks:
  omada:
    driver: bridge
