#!/bin/bash

PPATH="${OMADA_HOME}/properties"

# This might explode
echo 9999 > "${OMADA_HOME}/data/mongo.pid"

echo "========================="
echo "Creating directories"
echo "========================="
mkdir "${OMADA_HOME}/logs"
mkdir "${OMADA_HOME}/work"
mkdir -p "${OMADA_HOME}/data/autobackup"
touch "${OMADA_HOME}/logs/startup.log"

echo "========================="
echo "Overwriting configuration"
echo "========================="

echo "Setting OMADA_HTTP_PORT"
sed -i "s/^http\.connector\.port.*$/http.connector.port=${OMADA_HTTP_PORT}/g" "${PPATH}/jetty.properties"
echo "Setting OMADA_HTTPS_PORT"
sed -i "s/^https\.connector\.port.*$/https.connector.port=${OMADA_HTTPS_PORT}/g" "${PPATH}/jetty.properties"
# echo "Overwrite key.store.path"
# sed -i "s|^key\.store\.path.*$|key.store.path=${OMADA_HOME}/keystore/eap.keystore|g" "${PPATH}/jetty.properties"
# echo "Overwrite trust.store.path"
# sed -i "s|^trust\.store\.path.*$|trust.store.path=${OMADA_HOME}/keystore/eap.keystore|g" "${PPATH}/jetty.properties"
echo "Overwrite mongo.external"
sed -i "s/^#mongo\.external=.*$/mongo.external=true/g" "${PPATH}/eap.properties"
echo "Overwrite mongo.external.host"
sed -i "s/^#mongo\.external\.host=.*$/mongo.external.host=${OMADA_MONGO_HOST}/g" "${PPATH}/eap.properties"
echo "Overwrite mongo.external.port"
sed -i "s/^#mongo\.external\.port=.*$/mongo.external.port=${OMADA_MONGO_PORT}/g" "${PPATH}/eap.properties"
echo "Overwrite mongo.external.database"
sed -i "s/^#mongo\.external\.database=.*$/mongo.external.database=${OMADA_MONGO_DATABASE}/g" "${PPATH}/eap.properties"
echo "Overwrite eap.linux.mongod"
sed -i 's/^eap\.linux\.mongod=.*$/eap.linux.mongod="This is fine"/g' "${PPATH}/mongodb.properties"
echo "Overwrite eap.linux.mongo"
sed -i 's/^\(eap\.linux\.mongo=.*$\)/#\1/g' "${PPATH}/mongodb.properties"
echo "Overwrite eap.mongod.db"
sed -i 's/^\(eap\.mongod\.db.*$\)/#\1/g' "${PPATH}/mongodb.properties"
echo "Overwrite eap.mongod.port"
sed -i 's/^eap\.mongod\.port.*$/eap.mongod.port=27017/g' "${PPATH}/mongodb.properties"
echo "Overwrite eap.mongod.args"
sed -i 's/^eap\.mongod\.args.*$/eap.mongod.args="Really, trust me."/g' "${PPATH}/mongodb.properties"
echo "Overwrite eap.mongo.args"
sed -i 's/^\(eap\.mongo\.args.*$\)/#\1/g' "${PPATH}/mongodb.properties"
echo "Overwrite eap.mongod.reapair.command"
sed -i 's/^eap\.mongod\.repair\.command.*$/eap.mongod.repair.command="You really need to trust me."/g' "${PPATH}/mongodb.properties"
echo "Overwrite linux.mongod.nojournal"
sed -i 's/^\(linux\.mongod\.nojournal.*$\)/#\1/g' "${PPATH}/mongodb.properties"
echo "Overwrite appender.rolling.fileName"
sed -i "s|appender\.rolling\.fileName.*$|appender.rolling.fileName=${OMADA_HOME}/logs/server.log|g" "${PPATH}/log4j2.properties"
echo "Overwrite appender.rolling.filePattern"
sed -i "s|appender\.rolling\.filePattern.*$|appender.rolling.filePattern=${OMADA_HOME}/logs/server_%d{yyyy-MM-dd}_%i.log.gz|g" "${PPATH}/log4j2.properties"
echo "Overwrite appender.rolling.strategy.action.basepath"
sed -i "s|appender\.rolling\.strategy\.action\.basepath.*$|appender.rolling.strategy.action.basepath=${OMADA_HOME}/logs|g" "${PPATH}/log4j2.properties"

echo "========================="
echo "Creating omada uid/gid"
echo "========================="

groupadd -g 508 omada
useradd -u 508 -g 508 -d "${OMADA_HOME}" omada
chown -R omada:omada "${OMADA_HOME}"

echo "========================="
echo "Starting Java application"
echo "========================="

runuser -l omada -c "${OMADA_HOME}/jre/bin/java -server -Xms128m -Xmx1024m -XX:MaxHeapFreeRatio=60 -XX:MinHeapFreeRatio=30 -XX:+HeapDumpOnOutOfMemoryError -Deap.home=${OMADA_HOME} -cp /usr/share/java/commons-daemon.jar:${OMADA_HOME}/lib/*: com.tp_link.eap.start.EapLinuxMain start"
